# NumPy Assignment
**Name: Anhad Kohli**

In [ ]:
import numpy as np

## Q1: Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
- Addition of 2 to all elements
- Multiply 3 with all elements
- Divide every element by 2

In [ ]:
array = np.array([6, 10, 14, 16, 20])
print("Original Array:", array)
print("After Adding 2:", array + 2)
print("After Multiplying by 3:", array * 3)
print("After Dividing by 2:", array / 2)

**Answer:**
```
Original Array: [ 6 10 14 16 20]
After Adding 2: [ 8 12 16 18 22]
After Multiplying by 3: [18 30 42 48 60]
After Dividing by 2: [ 3.  5.  7.  8. 10.]
```

## Q2: Reverse the array arr = np.array([1, 2, 3, 6, 4, 5]). Find the most frequent value and their indices for:
- x = np.array([1,2,3,4,5,1,2,1,1,1])
- y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original Array:", arr)
print("Reversed Array:", arr[::-1])

**Answer:**
```
Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]
```

In [ ]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
unique_x, counts_x = np.unique(x, return_counts=True)
most_frequent_x = unique_x[np.argmax(counts_x)]
indices_x = np.where(x == most_frequent_x)[0]
print(f"Array x: {x}")
print(f"Most Frequent Element: {most_frequent_x}")
print(f"Indices: {indices_x}")

**Answer:**
```
Array x: [1 2 3 4 5 1 2 1 1 1]
Most Frequent Element: 1
Indices: [0 5 7 8 9]
```

In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
unique_y, counts_y = np.unique(y, return_counts=True)
most_frequent_y = unique_y[np.argmax(counts_y)]
indices_y = np.where(y == most_frequent_y)[0]
print(f"Array y: {y}")
print(f"Most Frequent Element: {most_frequent_y}")
print(f"Indices: {indices_y}")

**Answer:**
```
Array y: [1 1 1 2 3 4 2 4 3 3]
Most Frequent Element: 1
Indices: [0 1 2]
```

## Q3: For the given 2-D array, access elements using row and column indices

In [ ]:
arr3 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
print(arr3)
print(f"1st Row, 2nd Column [0,1]: {arr3[0, 1]}")
print(f"3rd Row, 1st Column [2,0]: {arr3[2, 0]}")

**Answer:**
```
[[10 20 30]
 [40 50 60]
 [70 80 90]]
1st Row, 2nd Column [0,1]: 20
3rd Row, 1st Column [2,0]: 70
```

## Q4: Create a 1-D NumPy array named AnhadKohli with 25 evenly spaced numbers from 10 to 100 using linspace(). Print dimensions, shape, total elements, data type, total bytes. Find transpose using reshape() and T attribute

In [ ]:
AnhadKohli = np.linspace(10, 100, 25)
print("Array:")
print(AnhadKohli)
print(f"Dimension: {AnhadKohli.ndim}")
print(f"Shape: {AnhadKohli.shape}")
print(f"Total Elements: {AnhadKohli.size}")
print(f"Data Type: {AnhadKohli.dtype}")
print(f"Total Bytes: {AnhadKohli.nbytes}")

**Answer:**
```
Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimension: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes: 200
```

In [ ]:
print("Transpose using reshape:")
print(AnhadKohli.reshape(25, 1))

**Answer:**
```
Transpose using reshape:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
```

In [ ]:
print("Transpose using T:")
print(AnhadKohli.T)

**Answer:**
```
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
```

## Q5: Create array ucs420_AnhadKohli with values [10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35]. Compute mean, median, max, min, unique elements. Reshape to 4x3 (reshaped_ucs420_AnhadKohli) and resize to 2x3 (resized_ucs420_AnhadKohli)

In [ ]:
ucs420_AnhadKohli = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35])
print(f"Mean: {np.mean(ucs420_AnhadKohli)}")
print(f"Median: {np.median(ucs420_AnhadKohli)}")
print(f"Max: {np.max(ucs420_AnhadKohli)}")
print(f"Min: {np.min(ucs420_AnhadKohli)}")
print(f"Unique Elements: {np.unique(ucs420_AnhadKohli)}")

**Answer:**
```
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
```

In [ ]:
reshaped_ucs420_AnhadKohli = ucs420_AnhadKohli.reshape(4, 3)
print("Reshaped (4x3):")
print(reshaped_ucs420_AnhadKohli)

**Answer:**
```
Reshaped (4x3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
```

In [ ]:
resized_ucs420_AnhadKohli = np.resize(ucs420_AnhadKohli, (2, 3))
print("Resized (2x3):")
print(resized_ucs420_AnhadKohli)

**Answer:**
```
Resized (2x3):
[[10 20 30]
 [40 50 60]]
```